# Generated by Django 4.2.7 on 2023-11-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="allowedSlots",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="spot",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spot",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="spot",
            name="name",
            field=models.CharField(default="", max_length=125),
        ),
    ]
