# Generated by Django 4.2.7 on 2023-12-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("show", "0008_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
