# Generated by Django 4.2.7 on 2023-12-02 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("show", "0009_feedback_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sent",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
