# Generated by Django 4.2.7 on 2023-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="f_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="l_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="id_number",
            field=models.TextField(default=-1),
        ),
    ]
