# Generated by Django 4.2.7 on 2023-12-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_userprofile_f_name_remove_userprofile_l_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="art_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
